DROP TABLE IF EXISTS todos CASCADE;

CREATE TABLE todos (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  creation_date DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  start_date DATE,
  end_date DATE,
  priority INTEGER NOT NULL DEFAULT 4,
  complete BOOLEAN NOT NULL DEFAULT FALSE,
  cover_photo_url VARCHAR(255),
  todo_id INTEGER REFERENCES todos(id),
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE NOT NULL
);
